[package]
name = "nomen"
version = "0.1.0"
edition = "2024"
version = "0.1.0"
authors = ["Jack Roddy <jack.w.roddy@gmail.com>"]
repository = "https://github.com/jackroddy/nomenn"
license = "MIT OR Apache-2.0"
description = "nomen is a TUI application for helping name software."


[dependencies]
ureq = "3.4"
flate2 = "1.1"
tar = "0.4"
ratatui = "0.30"
crossterm = "0.29"
